# USE THIS FOR DEVELOPMENT

version: "3"

services:
  hydra-server:
    container_name: "hydra-server"
    image: "hydra-server:latest"
    # make it privileged
    privileged: true
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
    tty: true
    ports:
      - "3100:3100"
    volumes:
      - type: bind
        source: ./test-config/config.toml
        target: /etc/hydra/config.toml
    networks:
      - hydra
  redis:
    container_name: redis
    image: redis
    networks:
      - hydra

networks:
  hydra:
    driver: bridge
