# USE THIS FOR DEVELOPMENT

version: "3"

services:
  hydra-server:
    container_name: "hydra-server"
    image: "hydra-server:latest"
    # make it privileged
    privileged: true
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
      - DOCKER=1
    tty: true
    ports:
      - "3100:3100"
    volumes:
      - type: bind
        source: ./test-config/config.toml
        target: /etc/hydra/config.toml
    networks:
      - hydra
    depends_on:
      - redis
  hydra-proxy:
    container_name: "hydra-proxy"
    image: "hydra-proxy:latest"
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3101:3101"
    networks:
      - hydra
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis
    networks:
      - hydra
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

networks:
  hydra:
    driver: bridge
