[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.152", features = ["serde_derive"] }
uuid = { version = "1.3.0", features = ["v4", "serde"] }
serde_json = "1.0.93"
