apiVersion: v1
kind: Pod

metadata:
  name: hydra-pod
spec:
  volumes:
    - name: hydra-configmap
      configMap:
        name: hydra-configmap
  containers:
    - name: hydra-server
      image: localhost:5000/hydra-server:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ENVIRONMENT
          value: production
        - name: DOCKER_HOST
          value: unix:///var/run/docker.sock
      volumeMounts:
        - mountPath: /etc/hydra/config.toml
          name: hydra-configmap
          subPath: config.toml
      securityContext:
        privileged: true
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
