[docker]
# Which CPUs to run containers on
cpu_set = "0"
# Microseconds of CPU time to give each container per CPU period
cpu_shares = 10000
# Memory to give each container (lowest 6MB)
memory = "128MB"

disk_read_rate = "10MB"
disk_write_rate = "10MB"
disk_max_size = "50MB"
