# USE THIS FOR DEVELOPMENT

version: "3"

services:
  hydra-server:
    container_name: "hydra-server"
    image: "hydra-server:latest"
    # make it privileged
    privileged: true
    environment:
      - ENVIRONMENT=development
      - DOCKER_HOST=tcp://localhost:2376
      - DOCKER_TLS_CERTDIR=/certs
    tty: true
    ports:
      - "3100:3100"
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - type: bind
        source: ../test-config/config.toml
        target: /etc/hydra/config.toml

volumes:
  docker-certs-ca:
  docker-certs-client:
